[package]
name = "scriptr"
version = "0.1.0"
authors = ["Farid Zakaria <farid.m.zakaria@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pty = "0.2"
nix = "0.18.0"
libc = "0.2.74"
simple-error = "0.2.1"
